[codespace]
# └─ Настройки переменных для кода или самой симуляции
world_x = 16
# ├─ Размер мира по X и Y
world_y = 8


[model]
# └─ Настройки переменных модели или Ollama
model = 'qwen3:1.7b'
# └─ Какая будет использоваться модель ИИ
CPU = 4
# └─ Сколько ядер CPU будет использоваться